# Generated by Django 2.1.7 on 2020-03-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0002_auto_20200324_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_date',
        ),
    ]
