# Generated by Django 2.1.7 on 2020-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0003_remove_user_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='star_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
